/*
 * generated by Xtext 2.12.0
 */
package org.xtext.robotFinal.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.robotFinal.parser.antlr.internal.InternalMarsRoverParser;
import org.xtext.robotFinal.services.MarsRoverGrammarAccess;

public class MarsRoverParser extends AbstractAntlrParser {

	@Inject
	private MarsRoverGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalMarsRoverParser createParser(XtextTokenStream stream) {
		return new InternalMarsRoverParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Robot";
	}

	public MarsRoverGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(MarsRoverGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
