/*
 * generated by Xtext 2.12.0
 */
package org.xtext.robotFinal.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class MarsRoverAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/xtext/robotFinal/parser/antlr/internal/InternalMarsRover.tokens");
	}
}
