/*
 * generated by Xtext 2.12.0
 */
package org.xtext.robotFinal.serializer;

import com.google.inject.Inject;
import java.util.List;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.xtext.IGrammarAccess;
import org.eclipse.xtext.RuleCall;
import org.eclipse.xtext.nodemodel.INode;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.AbstractElementAlias;
import org.eclipse.xtext.serializer.analysis.GrammarAlias.TokenAlias;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynNavigable;
import org.eclipse.xtext.serializer.analysis.ISyntacticSequencerPDAProvider.ISynTransition;
import org.eclipse.xtext.serializer.sequencer.AbstractSyntacticSequencer;
import org.xtext.robotFinal.services.MarsRoverGrammarAccess;

@SuppressWarnings("all")
public class MarsRoverSyntacticSequencer extends AbstractSyntacticSequencer {

	protected MarsRoverGrammarAccess grammarAccess;
	protected AbstractElementAlias match_after_action_IndicateKeyword_1_0_q;
	
	@Inject
	protected void init(IGrammarAccess access) {
		grammarAccess = (MarsRoverGrammarAccess) access;
		match_after_action_IndicateKeyword_1_0_q = new TokenAlias(false, true, grammarAccess.getAfter_actionAccess().getIndicateKeyword_1_0());
	}
	
	@Override
	protected String getUnassignedRuleCallToken(EObject semanticObject, RuleCall ruleCall, INode node) {
		return "";
	}
	
	
	@Override
	protected void emitUnassignedTokens(EObject semanticObject, ISynTransition transition, INode fromNode, INode toNode) {
		if (transition.getAmbiguousSyntaxes().isEmpty()) return;
		List<INode> transitionNodes = collectNodes(fromNode, toNode);
		for (AbstractElementAlias syntax : transition.getAmbiguousSyntaxes()) {
			List<INode> syntaxNodes = getNodesFor(transitionNodes, syntax);
			if (match_after_action_IndicateKeyword_1_0_q.equals(syntax))
				emit_after_action_IndicateKeyword_1_0_q(semanticObject, getLastNavigableState(), syntaxNodes);
			else acceptNodes(getLastNavigableState(), syntaxNodes);
		}
	}

	/**
	 * Ambiguous syntax:
	 *     'indicate'?
	 *
	 * This ambiguous syntax occurs at:
	 *     action='continue' (ambiguity) (rule end)
	 *     action='stop' (ambiguity) (rule end)
	 */
	protected void emit_after_action_IndicateKeyword_1_0_q(EObject semanticObject, ISynNavigable transition, List<INode> nodes) {
		acceptNodes(transition, nodes);
	}
	
}
