/*
 * generated by Xtext 2.12.0
 */
package org.xtext.robotFinal.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.xtext.robotFinal.ui.internal.RobotFinalActivator;

public class MarsRoverUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return RobotFinalActivator.getInstance().getInjector("org.xtext.robotFinal.MarsRover");
	}

}
