/**
 * generated by Xtext 2.12.0
 */
package org.xtext.robotFinal.marsRover.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;
import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.xtext.robotFinal.marsRover.MarsRoverPackage;
import org.xtext.robotFinal.marsRover.Robot;
import org.xtext.robotFinal.marsRover.mission;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Robot</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.robotFinal.marsRover.impl.RobotImpl#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.robotFinal.marsRover.impl.RobotImpl#getSlave_address <em>Slave address</em>}</li>
 *   <li>{@link org.xtext.robotFinal.marsRover.impl.RobotImpl#getDrive_speed <em>Drive speed</em>}</li>
 *   <li>{@link org.xtext.robotFinal.marsRover.impl.RobotImpl#getSpecial_speed <em>Special speed</em>}</li>
 *   <li>{@link org.xtext.robotFinal.marsRover.impl.RobotImpl#getMissions <em>Missions</em>}</li>
 * </ul>
 *
 * @generated
 */
public class RobotImpl extends MinimalEObjectImpl.Container implements Robot
{
  /**
   * The default value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected static final String NAME_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getName() <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getName()
   * @generated
   * @ordered
   */
  protected String name = NAME_EDEFAULT;

  /**
   * The default value of the '{@link #getSlave_address() <em>Slave address</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSlave_address()
   * @generated
   * @ordered
   */
  protected static final String SLAVE_ADDRESS_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getSlave_address() <em>Slave address</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSlave_address()
   * @generated
   * @ordered
   */
  protected String slave_address = SLAVE_ADDRESS_EDEFAULT;

  /**
   * The default value of the '{@link #getDrive_speed() <em>Drive speed</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDrive_speed()
   * @generated
   * @ordered
   */
  protected static final int DRIVE_SPEED_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getDrive_speed() <em>Drive speed</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getDrive_speed()
   * @generated
   * @ordered
   */
  protected int drive_speed = DRIVE_SPEED_EDEFAULT;

  /**
   * The default value of the '{@link #getSpecial_speed() <em>Special speed</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSpecial_speed()
   * @generated
   * @ordered
   */
  protected static final int SPECIAL_SPEED_EDEFAULT = 0;

  /**
   * The cached value of the '{@link #getSpecial_speed() <em>Special speed</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getSpecial_speed()
   * @generated
   * @ordered
   */
  protected int special_speed = SPECIAL_SPEED_EDEFAULT;

  /**
   * The cached value of the '{@link #getMissions() <em>Missions</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getMissions()
   * @generated
   * @ordered
   */
  protected EList<mission> missions;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected RobotImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return MarsRoverPackage.Literals.ROBOT;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getName()
  {
    return name;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setName(String newName)
  {
    String oldName = name;
    name = newName;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MarsRoverPackage.ROBOT__NAME, oldName, name));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public String getSlave_address()
  {
    return slave_address;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSlave_address(String newSlave_address)
  {
    String oldSlave_address = slave_address;
    slave_address = newSlave_address;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MarsRoverPackage.ROBOT__SLAVE_ADDRESS, oldSlave_address, slave_address));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getDrive_speed()
  {
    return drive_speed;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setDrive_speed(int newDrive_speed)
  {
    int oldDrive_speed = drive_speed;
    drive_speed = newDrive_speed;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MarsRoverPackage.ROBOT__DRIVE_SPEED, oldDrive_speed, drive_speed));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public int getSpecial_speed()
  {
    return special_speed;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public void setSpecial_speed(int newSpecial_speed)
  {
    int oldSpecial_speed = special_speed;
    special_speed = newSpecial_speed;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, MarsRoverPackage.ROBOT__SPECIAL_SPEED, oldSpecial_speed, special_speed));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public EList<mission> getMissions()
  {
    if (missions == null)
    {
      missions = new EObjectContainmentEList<mission>(mission.class, this, MarsRoverPackage.ROBOT__MISSIONS);
    }
    return missions;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case MarsRoverPackage.ROBOT__MISSIONS:
        return ((InternalEList<?>)getMissions()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case MarsRoverPackage.ROBOT__NAME:
        return getName();
      case MarsRoverPackage.ROBOT__SLAVE_ADDRESS:
        return getSlave_address();
      case MarsRoverPackage.ROBOT__DRIVE_SPEED:
        return getDrive_speed();
      case MarsRoverPackage.ROBOT__SPECIAL_SPEED:
        return getSpecial_speed();
      case MarsRoverPackage.ROBOT__MISSIONS:
        return getMissions();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case MarsRoverPackage.ROBOT__NAME:
        setName((String)newValue);
        return;
      case MarsRoverPackage.ROBOT__SLAVE_ADDRESS:
        setSlave_address((String)newValue);
        return;
      case MarsRoverPackage.ROBOT__DRIVE_SPEED:
        setDrive_speed((Integer)newValue);
        return;
      case MarsRoverPackage.ROBOT__SPECIAL_SPEED:
        setSpecial_speed((Integer)newValue);
        return;
      case MarsRoverPackage.ROBOT__MISSIONS:
        getMissions().clear();
        getMissions().addAll((Collection<? extends mission>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case MarsRoverPackage.ROBOT__NAME:
        setName(NAME_EDEFAULT);
        return;
      case MarsRoverPackage.ROBOT__SLAVE_ADDRESS:
        setSlave_address(SLAVE_ADDRESS_EDEFAULT);
        return;
      case MarsRoverPackage.ROBOT__DRIVE_SPEED:
        setDrive_speed(DRIVE_SPEED_EDEFAULT);
        return;
      case MarsRoverPackage.ROBOT__SPECIAL_SPEED:
        setSpecial_speed(SPECIAL_SPEED_EDEFAULT);
        return;
      case MarsRoverPackage.ROBOT__MISSIONS:
        getMissions().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case MarsRoverPackage.ROBOT__NAME:
        return NAME_EDEFAULT == null ? name != null : !NAME_EDEFAULT.equals(name);
      case MarsRoverPackage.ROBOT__SLAVE_ADDRESS:
        return SLAVE_ADDRESS_EDEFAULT == null ? slave_address != null : !SLAVE_ADDRESS_EDEFAULT.equals(slave_address);
      case MarsRoverPackage.ROBOT__DRIVE_SPEED:
        return drive_speed != DRIVE_SPEED_EDEFAULT;
      case MarsRoverPackage.ROBOT__SPECIAL_SPEED:
        return special_speed != SPECIAL_SPEED_EDEFAULT;
      case MarsRoverPackage.ROBOT__MISSIONS:
        return missions != null && !missions.isEmpty();
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuffer result = new StringBuffer(super.toString());
    result.append(" (name: ");
    result.append(name);
    result.append(", slave_address: ");
    result.append(slave_address);
    result.append(", drive_speed: ");
    result.append(drive_speed);
    result.append(", special_speed: ");
    result.append(special_speed);
    result.append(')');
    return result.toString();
  }

} //RobotImpl
