/*
 * generated by Xtext 2.12.0
 */
package org.xtext.robotFinal


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class MarsRoverStandaloneSetup extends MarsRoverStandaloneSetupGenerated {

	def static void doSetup() {
		new MarsRoverStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
