/**
 * generated by Xtext 2.12.0
 */
package org.xtext.robotFinal.marsRover;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>after action</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.robotFinal.marsRover.after_action#getAction <em>Action</em>}</li>
 *   <li>{@link org.xtext.robotFinal.marsRover.after_action#getIndicate <em>Indicate</em>}</li>
 * </ul>
 *
 * @see org.xtext.robotFinal.marsRover.MarsRoverPackage#getafter_action()
 * @model
 * @generated
 */
public interface after_action extends EObject
{
  /**
   * Returns the value of the '<em><b>Action</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Action</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Action</em>' attribute.
   * @see #setAction(String)
   * @see org.xtext.robotFinal.marsRover.MarsRoverPackage#getafter_action_Action()
   * @model
   * @generated
   */
  String getAction();

  /**
   * Sets the value of the '{@link org.xtext.robotFinal.marsRover.after_action#getAction <em>Action</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Action</em>' attribute.
   * @see #getAction()
   * @generated
   */
  void setAction(String value);

  /**
   * Returns the value of the '<em><b>Indicate</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.robotFinal.marsRover.indication}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Indicate</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Indicate</em>' containment reference list.
   * @see org.xtext.robotFinal.marsRover.MarsRoverPackage#getafter_action_Indicate()
   * @model containment="true"
   * @generated
   */
  EList<indication> getIndicate();

} // after_action
