/**
 * generated by Xtext 2.12.0
 */
package org.xtext.robotFinal.marsRover;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>detect rocks</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.robotFinal.marsRover.detect_rocks#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.robotFinal.marsRover.detect_rocks#getNumber_of_rocks <em>Number of rocks</em>}</li>
 *   <li>{@link org.xtext.robotFinal.marsRover.detect_rocks#getAfter_examinating <em>After examinating</em>}</li>
 * </ul>
 *
 * @see org.xtext.robotFinal.marsRover.MarsRoverPackage#getdetect_rocks()
 * @model
 * @generated
 */
public interface detect_rocks extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.robotFinal.marsRover.MarsRoverPackage#getdetect_rocks_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.robotFinal.marsRover.detect_rocks#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Number of rocks</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Number of rocks</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Number of rocks</em>' attribute.
   * @see #setNumber_of_rocks(int)
   * @see org.xtext.robotFinal.marsRover.MarsRoverPackage#getdetect_rocks_Number_of_rocks()
   * @model
   * @generated
   */
  int getNumber_of_rocks();

  /**
   * Sets the value of the '{@link org.xtext.robotFinal.marsRover.detect_rocks#getNumber_of_rocks <em>Number of rocks</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Number of rocks</em>' attribute.
   * @see #getNumber_of_rocks()
   * @generated
   */
  void setNumber_of_rocks(int value);

  /**
   * Returns the value of the '<em><b>After examinating</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>After examinating</em>' containment reference isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>After examinating</em>' containment reference.
   * @see #setAfter_examinating(after_action)
   * @see org.xtext.robotFinal.marsRover.MarsRoverPackage#getdetect_rocks_After_examinating()
   * @model containment="true"
   * @generated
   */
  after_action getAfter_examinating();

  /**
   * Sets the value of the '{@link org.xtext.robotFinal.marsRover.detect_rocks#getAfter_examinating <em>After examinating</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>After examinating</em>' containment reference.
   * @see #getAfter_examinating()
   * @generated
   */
  void setAfter_examinating(after_action value);

} // detect_rocks
