/**
 * generated by Xtext 2.12.0
 */
package org.xtext.robotFinal.marsRover;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EEnum;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.xtext.robotFinal.marsRover.MarsRoverFactory
 * @model kind="package"
 * @generated
 */
public interface MarsRoverPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "marsRover";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.xtext.org/robotFinal/MarsRover";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "marsRover";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MarsRoverPackage eINSTANCE = org.xtext.robotFinal.marsRover.impl.MarsRoverPackageImpl.init();

  /**
   * The meta object id for the '{@link org.xtext.robotFinal.marsRover.impl.RobotImpl <em>Robot</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.robotFinal.marsRover.impl.RobotImpl
   * @see org.xtext.robotFinal.marsRover.impl.MarsRoverPackageImpl#getRobot()
   * @generated
   */
  int ROBOT = 0;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROBOT__NAME = 0;

  /**
   * The feature id for the '<em><b>Slave address</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROBOT__SLAVE_ADDRESS = 1;

  /**
   * The feature id for the '<em><b>Drive speed</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROBOT__DRIVE_SPEED = 2;

  /**
   * The feature id for the '<em><b>Special speed</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROBOT__SPECIAL_SPEED = 3;

  /**
   * The feature id for the '<em><b>Missions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROBOT__MISSIONS = 4;

  /**
   * The number of structural features of the '<em>Robot</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ROBOT_FEATURE_COUNT = 5;

  /**
   * The meta object id for the '{@link org.xtext.robotFinal.marsRover.impl.missionImpl <em>mission</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.robotFinal.marsRover.impl.missionImpl
   * @see org.xtext.robotFinal.marsRover.impl.MarsRoverPackageImpl#getmission()
   * @generated
   */
  int MISSION = 1;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION__TYPE = 1;

  /**
   * The number of structural features of the '<em>mission</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MISSION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.robotFinal.marsRover.impl.avoid_obstaclesImpl <em>avoid obstacles</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.robotFinal.marsRover.impl.avoid_obstaclesImpl
   * @see org.xtext.robotFinal.marsRover.impl.MarsRoverPackageImpl#getavoid_obstacles()
   * @generated
   */
  int AVOID_OBSTACLES = 2;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AVOID_OBSTACLES__NAME = 0;

  /**
   * The feature id for the '<em><b>Sensors</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AVOID_OBSTACLES__SENSORS = 1;

  /**
   * The number of structural features of the '<em>avoid obstacles</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AVOID_OBSTACLES_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.robotFinal.marsRover.impl.ultraImpl <em>ultra</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.robotFinal.marsRover.impl.ultraImpl
   * @see org.xtext.robotFinal.marsRover.impl.MarsRoverPackageImpl#getultra()
   * @generated
   */
  int ULTRA = 3;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ULTRA__NAME = 0;

  /**
   * The feature id for the '<em><b>Distance</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ULTRA__DISTANCE = 1;

  /**
   * The number of structural features of the '<em>ultra</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int ULTRA_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.robotFinal.marsRover.impl.bumpersImpl <em>bumpers</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.robotFinal.marsRover.impl.bumpersImpl
   * @see org.xtext.robotFinal.marsRover.impl.MarsRoverPackageImpl#getbumpers()
   * @generated
   */
  int BUMPERS = 4;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUMPERS__NAME = 0;

  /**
   * The number of structural features of the '<em>bumpers</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int BUMPERS_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.robotFinal.marsRover.impl.detect_lakesImpl <em>detect lakes</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.robotFinal.marsRover.impl.detect_lakesImpl
   * @see org.xtext.robotFinal.marsRover.impl.MarsRoverPackageImpl#getdetect_lakes()
   * @generated
   */
  int DETECT_LAKES = 5;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DETECT_LAKES__NAME = 0;

  /**
   * The feature id for the '<em><b>Number of lakes</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DETECT_LAKES__NUMBER_OF_LAKES = 1;

  /**
   * The feature id for the '<em><b>Lakes colors</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DETECT_LAKES__LAKES_COLORS = 2;

  /**
   * The feature id for the '<em><b>After examinating</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DETECT_LAKES__AFTER_EXAMINATING = 3;

  /**
   * The number of structural features of the '<em>detect lakes</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DETECT_LAKES_FEATURE_COUNT = 4;

  /**
   * The meta object id for the '{@link org.xtext.robotFinal.marsRover.impl.detect_rocksImpl <em>detect rocks</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.robotFinal.marsRover.impl.detect_rocksImpl
   * @see org.xtext.robotFinal.marsRover.impl.MarsRoverPackageImpl#getdetect_rocks()
   * @generated
   */
  int DETECT_ROCKS = 6;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DETECT_ROCKS__NAME = 0;

  /**
   * The feature id for the '<em><b>Number of rocks</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DETECT_ROCKS__NUMBER_OF_ROCKS = 1;

  /**
   * The feature id for the '<em><b>After examinating</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DETECT_ROCKS__AFTER_EXAMINATING = 2;

  /**
   * The number of structural features of the '<em>detect rocks</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int DETECT_ROCKS_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.robotFinal.marsRover.impl.push_obstaclesImpl <em>push obstacles</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.robotFinal.marsRover.impl.push_obstaclesImpl
   * @see org.xtext.robotFinal.marsRover.impl.MarsRoverPackageImpl#getpush_obstacles()
   * @generated
   */
  int PUSH_OBSTACLES = 7;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PUSH_OBSTACLES__NAME = 0;

  /**
   * The number of structural features of the '<em>push obstacles</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PUSH_OBSTACLES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.robotFinal.marsRover.impl.after_actionImpl <em>after action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.robotFinal.marsRover.impl.after_actionImpl
   * @see org.xtext.robotFinal.marsRover.impl.MarsRoverPackageImpl#getafter_action()
   * @generated
   */
  int AFTER_ACTION = 8;

  /**
   * The feature id for the '<em><b>Action</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AFTER_ACTION__ACTION = 0;

  /**
   * The feature id for the '<em><b>Indicate</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AFTER_ACTION__INDICATE = 1;

  /**
   * The number of structural features of the '<em>after action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AFTER_ACTION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.robotFinal.marsRover.impl.indicationImpl <em>indication</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.robotFinal.marsRover.impl.indicationImpl
   * @see org.xtext.robotFinal.marsRover.impl.MarsRoverPackageImpl#getindication()
   * @generated
   */
  int INDICATION = 9;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INDICATION__NAME = 0;

  /**
   * The feature id for the '<em><b>Type</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INDICATION__TYPE = 1;

  /**
   * The number of structural features of the '<em>indication</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int INDICATION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.robotFinal.marsRover.impl.soundImpl <em>sound</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.robotFinal.marsRover.impl.soundImpl
   * @see org.xtext.robotFinal.marsRover.impl.MarsRoverPackageImpl#getsound()
   * @generated
   */
  int SOUND = 10;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOUND__NAME = 0;

  /**
   * The feature id for the '<em><b>Duration</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOUND__DURATION = 1;

  /**
   * The feature id for the '<em><b>Frequency</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOUND__FREQUENCY = 2;

  /**
   * The number of structural features of the '<em>sound</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SOUND_FEATURE_COUNT = 3;

  /**
   * The meta object id for the '{@link org.xtext.robotFinal.marsRover.impl.messageImpl <em>message</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.robotFinal.marsRover.impl.messageImpl
   * @see org.xtext.robotFinal.marsRover.impl.MarsRoverPackageImpl#getmessage()
   * @generated
   */
  int MESSAGE = 11;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE__NAME = 0;

  /**
   * The feature id for the '<em><b>Msg</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE__MSG = 1;

  /**
   * The number of structural features of the '<em>message</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int MESSAGE_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.robotFinal.marsRover.impl.color_indicationImpl <em>color indication</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.robotFinal.marsRover.impl.color_indicationImpl
   * @see org.xtext.robotFinal.marsRover.impl.MarsRoverPackageImpl#getcolor_indication()
   * @generated
   */
  int COLOR_INDICATION = 12;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLOR_INDICATION__NAME = 0;

  /**
   * The feature id for the '<em><b>Color</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLOR_INDICATION__COLOR = 1;

  /**
   * The number of structural features of the '<em>color indication</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLOR_INDICATION_FEATURE_COUNT = 2;

  /**
   * The meta object id for the '{@link org.xtext.robotFinal.marsRover.impl.parkImpl <em>park</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.robotFinal.marsRover.impl.parkImpl
   * @see org.xtext.robotFinal.marsRover.impl.MarsRoverPackageImpl#getpark()
   * @generated
   */
  int PARK = 13;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARK__NAME = 0;

  /**
   * The number of structural features of the '<em>park</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int PARK_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.robotFinal.marsRover.impl.avoid_lakesImpl <em>avoid lakes</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.robotFinal.marsRover.impl.avoid_lakesImpl
   * @see org.xtext.robotFinal.marsRover.impl.MarsRoverPackageImpl#getavoid_lakes()
   * @generated
   */
  int AVOID_LAKES = 14;

  /**
   * The feature id for the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AVOID_LAKES__NAME = 0;

  /**
   * The number of structural features of the '<em>avoid lakes</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int AVOID_LAKES_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.xtext.robotFinal.marsRover.Color <em>Color</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.robotFinal.marsRover.Color
   * @see org.xtext.robotFinal.marsRover.impl.MarsRoverPackageImpl#getColor()
   * @generated
   */
  int COLOR = 15;

  /**
   * The meta object id for the '{@link org.xtext.robotFinal.marsRover.LED_Color <em>LED Color</em>}' enum.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.xtext.robotFinal.marsRover.LED_Color
   * @see org.xtext.robotFinal.marsRover.impl.MarsRoverPackageImpl#getLED_Color()
   * @generated
   */
  int LED_COLOR = 16;


  /**
   * Returns the meta object for class '{@link org.xtext.robotFinal.marsRover.Robot <em>Robot</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Robot</em>'.
   * @see org.xtext.robotFinal.marsRover.Robot
   * @generated
   */
  EClass getRobot();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.robotFinal.marsRover.Robot#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.robotFinal.marsRover.Robot#getName()
   * @see #getRobot()
   * @generated
   */
  EAttribute getRobot_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.robotFinal.marsRover.Robot#getSlave_address <em>Slave address</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Slave address</em>'.
   * @see org.xtext.robotFinal.marsRover.Robot#getSlave_address()
   * @see #getRobot()
   * @generated
   */
  EAttribute getRobot_Slave_address();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.robotFinal.marsRover.Robot#getDrive_speed <em>Drive speed</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Drive speed</em>'.
   * @see org.xtext.robotFinal.marsRover.Robot#getDrive_speed()
   * @see #getRobot()
   * @generated
   */
  EAttribute getRobot_Drive_speed();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.robotFinal.marsRover.Robot#getSpecial_speed <em>Special speed</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Special speed</em>'.
   * @see org.xtext.robotFinal.marsRover.Robot#getSpecial_speed()
   * @see #getRobot()
   * @generated
   */
  EAttribute getRobot_Special_speed();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.robotFinal.marsRover.Robot#getMissions <em>Missions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Missions</em>'.
   * @see org.xtext.robotFinal.marsRover.Robot#getMissions()
   * @see #getRobot()
   * @generated
   */
  EReference getRobot_Missions();

  /**
   * Returns the meta object for class '{@link org.xtext.robotFinal.marsRover.mission <em>mission</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>mission</em>'.
   * @see org.xtext.robotFinal.marsRover.mission
   * @generated
   */
  EClass getmission();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.robotFinal.marsRover.mission#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.robotFinal.marsRover.mission#getName()
   * @see #getmission()
   * @generated
   */
  EAttribute getmission_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.robotFinal.marsRover.mission#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see org.xtext.robotFinal.marsRover.mission#getType()
   * @see #getmission()
   * @generated
   */
  EReference getmission_Type();

  /**
   * Returns the meta object for class '{@link org.xtext.robotFinal.marsRover.avoid_obstacles <em>avoid obstacles</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>avoid obstacles</em>'.
   * @see org.xtext.robotFinal.marsRover.avoid_obstacles
   * @generated
   */
  EClass getavoid_obstacles();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.robotFinal.marsRover.avoid_obstacles#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.robotFinal.marsRover.avoid_obstacles#getName()
   * @see #getavoid_obstacles()
   * @generated
   */
  EAttribute getavoid_obstacles_Name();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.robotFinal.marsRover.avoid_obstacles#getSensors <em>Sensors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Sensors</em>'.
   * @see org.xtext.robotFinal.marsRover.avoid_obstacles#getSensors()
   * @see #getavoid_obstacles()
   * @generated
   */
  EReference getavoid_obstacles_Sensors();

  /**
   * Returns the meta object for class '{@link org.xtext.robotFinal.marsRover.ultra <em>ultra</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>ultra</em>'.
   * @see org.xtext.robotFinal.marsRover.ultra
   * @generated
   */
  EClass getultra();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.robotFinal.marsRover.ultra#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.robotFinal.marsRover.ultra#getName()
   * @see #getultra()
   * @generated
   */
  EAttribute getultra_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.robotFinal.marsRover.ultra#getDistance <em>Distance</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Distance</em>'.
   * @see org.xtext.robotFinal.marsRover.ultra#getDistance()
   * @see #getultra()
   * @generated
   */
  EAttribute getultra_Distance();

  /**
   * Returns the meta object for class '{@link org.xtext.robotFinal.marsRover.bumpers <em>bumpers</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>bumpers</em>'.
   * @see org.xtext.robotFinal.marsRover.bumpers
   * @generated
   */
  EClass getbumpers();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.robotFinal.marsRover.bumpers#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.robotFinal.marsRover.bumpers#getName()
   * @see #getbumpers()
   * @generated
   */
  EAttribute getbumpers_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.robotFinal.marsRover.detect_lakes <em>detect lakes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>detect lakes</em>'.
   * @see org.xtext.robotFinal.marsRover.detect_lakes
   * @generated
   */
  EClass getdetect_lakes();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.robotFinal.marsRover.detect_lakes#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.robotFinal.marsRover.detect_lakes#getName()
   * @see #getdetect_lakes()
   * @generated
   */
  EAttribute getdetect_lakes_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.robotFinal.marsRover.detect_lakes#getNumber_of_lakes <em>Number of lakes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Number of lakes</em>'.
   * @see org.xtext.robotFinal.marsRover.detect_lakes#getNumber_of_lakes()
   * @see #getdetect_lakes()
   * @generated
   */
  EAttribute getdetect_lakes_Number_of_lakes();

  /**
   * Returns the meta object for the attribute list '{@link org.xtext.robotFinal.marsRover.detect_lakes#getLakes_colors <em>Lakes colors</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Lakes colors</em>'.
   * @see org.xtext.robotFinal.marsRover.detect_lakes#getLakes_colors()
   * @see #getdetect_lakes()
   * @generated
   */
  EAttribute getdetect_lakes_Lakes_colors();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.robotFinal.marsRover.detect_lakes#getAfter_examinating <em>After examinating</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>After examinating</em>'.
   * @see org.xtext.robotFinal.marsRover.detect_lakes#getAfter_examinating()
   * @see #getdetect_lakes()
   * @generated
   */
  EReference getdetect_lakes_After_examinating();

  /**
   * Returns the meta object for class '{@link org.xtext.robotFinal.marsRover.detect_rocks <em>detect rocks</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>detect rocks</em>'.
   * @see org.xtext.robotFinal.marsRover.detect_rocks
   * @generated
   */
  EClass getdetect_rocks();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.robotFinal.marsRover.detect_rocks#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.robotFinal.marsRover.detect_rocks#getName()
   * @see #getdetect_rocks()
   * @generated
   */
  EAttribute getdetect_rocks_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.robotFinal.marsRover.detect_rocks#getNumber_of_rocks <em>Number of rocks</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Number of rocks</em>'.
   * @see org.xtext.robotFinal.marsRover.detect_rocks#getNumber_of_rocks()
   * @see #getdetect_rocks()
   * @generated
   */
  EAttribute getdetect_rocks_Number_of_rocks();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.robotFinal.marsRover.detect_rocks#getAfter_examinating <em>After examinating</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>After examinating</em>'.
   * @see org.xtext.robotFinal.marsRover.detect_rocks#getAfter_examinating()
   * @see #getdetect_rocks()
   * @generated
   */
  EReference getdetect_rocks_After_examinating();

  /**
   * Returns the meta object for class '{@link org.xtext.robotFinal.marsRover.push_obstacles <em>push obstacles</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>push obstacles</em>'.
   * @see org.xtext.robotFinal.marsRover.push_obstacles
   * @generated
   */
  EClass getpush_obstacles();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.robotFinal.marsRover.push_obstacles#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.robotFinal.marsRover.push_obstacles#getName()
   * @see #getpush_obstacles()
   * @generated
   */
  EAttribute getpush_obstacles_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.robotFinal.marsRover.after_action <em>after action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>after action</em>'.
   * @see org.xtext.robotFinal.marsRover.after_action
   * @generated
   */
  EClass getafter_action();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.robotFinal.marsRover.after_action#getAction <em>Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Action</em>'.
   * @see org.xtext.robotFinal.marsRover.after_action#getAction()
   * @see #getafter_action()
   * @generated
   */
  EAttribute getafter_action_Action();

  /**
   * Returns the meta object for the containment reference list '{@link org.xtext.robotFinal.marsRover.after_action#getIndicate <em>Indicate</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Indicate</em>'.
   * @see org.xtext.robotFinal.marsRover.after_action#getIndicate()
   * @see #getafter_action()
   * @generated
   */
  EReference getafter_action_Indicate();

  /**
   * Returns the meta object for class '{@link org.xtext.robotFinal.marsRover.indication <em>indication</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>indication</em>'.
   * @see org.xtext.robotFinal.marsRover.indication
   * @generated
   */
  EClass getindication();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.robotFinal.marsRover.indication#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.robotFinal.marsRover.indication#getName()
   * @see #getindication()
   * @generated
   */
  EAttribute getindication_Name();

  /**
   * Returns the meta object for the containment reference '{@link org.xtext.robotFinal.marsRover.indication#getType <em>Type</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Type</em>'.
   * @see org.xtext.robotFinal.marsRover.indication#getType()
   * @see #getindication()
   * @generated
   */
  EReference getindication_Type();

  /**
   * Returns the meta object for class '{@link org.xtext.robotFinal.marsRover.sound <em>sound</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>sound</em>'.
   * @see org.xtext.robotFinal.marsRover.sound
   * @generated
   */
  EClass getsound();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.robotFinal.marsRover.sound#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.robotFinal.marsRover.sound#getName()
   * @see #getsound()
   * @generated
   */
  EAttribute getsound_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.robotFinal.marsRover.sound#getDuration <em>Duration</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Duration</em>'.
   * @see org.xtext.robotFinal.marsRover.sound#getDuration()
   * @see #getsound()
   * @generated
   */
  EAttribute getsound_Duration();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.robotFinal.marsRover.sound#getFrequency <em>Frequency</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Frequency</em>'.
   * @see org.xtext.robotFinal.marsRover.sound#getFrequency()
   * @see #getsound()
   * @generated
   */
  EAttribute getsound_Frequency();

  /**
   * Returns the meta object for class '{@link org.xtext.robotFinal.marsRover.message <em>message</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>message</em>'.
   * @see org.xtext.robotFinal.marsRover.message
   * @generated
   */
  EClass getmessage();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.robotFinal.marsRover.message#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.robotFinal.marsRover.message#getName()
   * @see #getmessage()
   * @generated
   */
  EAttribute getmessage_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.robotFinal.marsRover.message#getMsg <em>Msg</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Msg</em>'.
   * @see org.xtext.robotFinal.marsRover.message#getMsg()
   * @see #getmessage()
   * @generated
   */
  EAttribute getmessage_Msg();

  /**
   * Returns the meta object for class '{@link org.xtext.robotFinal.marsRover.color_indication <em>color indication</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>color indication</em>'.
   * @see org.xtext.robotFinal.marsRover.color_indication
   * @generated
   */
  EClass getcolor_indication();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.robotFinal.marsRover.color_indication#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.robotFinal.marsRover.color_indication#getName()
   * @see #getcolor_indication()
   * @generated
   */
  EAttribute getcolor_indication_Name();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.robotFinal.marsRover.color_indication#getColor <em>Color</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Color</em>'.
   * @see org.xtext.robotFinal.marsRover.color_indication#getColor()
   * @see #getcolor_indication()
   * @generated
   */
  EAttribute getcolor_indication_Color();

  /**
   * Returns the meta object for class '{@link org.xtext.robotFinal.marsRover.park <em>park</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>park</em>'.
   * @see org.xtext.robotFinal.marsRover.park
   * @generated
   */
  EClass getpark();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.robotFinal.marsRover.park#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.robotFinal.marsRover.park#getName()
   * @see #getpark()
   * @generated
   */
  EAttribute getpark_Name();

  /**
   * Returns the meta object for class '{@link org.xtext.robotFinal.marsRover.avoid_lakes <em>avoid lakes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>avoid lakes</em>'.
   * @see org.xtext.robotFinal.marsRover.avoid_lakes
   * @generated
   */
  EClass getavoid_lakes();

  /**
   * Returns the meta object for the attribute '{@link org.xtext.robotFinal.marsRover.avoid_lakes#getName <em>Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Name</em>'.
   * @see org.xtext.robotFinal.marsRover.avoid_lakes#getName()
   * @see #getavoid_lakes()
   * @generated
   */
  EAttribute getavoid_lakes_Name();

  /**
   * Returns the meta object for enum '{@link org.xtext.robotFinal.marsRover.Color <em>Color</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>Color</em>'.
   * @see org.xtext.robotFinal.marsRover.Color
   * @generated
   */
  EEnum getColor();

  /**
   * Returns the meta object for enum '{@link org.xtext.robotFinal.marsRover.LED_Color <em>LED Color</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for enum '<em>LED Color</em>'.
   * @see org.xtext.robotFinal.marsRover.LED_Color
   * @generated
   */
  EEnum getLED_Color();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  MarsRoverFactory getMarsRoverFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.xtext.robotFinal.marsRover.impl.RobotImpl <em>Robot</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.robotFinal.marsRover.impl.RobotImpl
     * @see org.xtext.robotFinal.marsRover.impl.MarsRoverPackageImpl#getRobot()
     * @generated
     */
    EClass ROBOT = eINSTANCE.getRobot();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROBOT__NAME = eINSTANCE.getRobot_Name();

    /**
     * The meta object literal for the '<em><b>Slave address</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROBOT__SLAVE_ADDRESS = eINSTANCE.getRobot_Slave_address();

    /**
     * The meta object literal for the '<em><b>Drive speed</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROBOT__DRIVE_SPEED = eINSTANCE.getRobot_Drive_speed();

    /**
     * The meta object literal for the '<em><b>Special speed</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ROBOT__SPECIAL_SPEED = eINSTANCE.getRobot_Special_speed();

    /**
     * The meta object literal for the '<em><b>Missions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference ROBOT__MISSIONS = eINSTANCE.getRobot_Missions();

    /**
     * The meta object literal for the '{@link org.xtext.robotFinal.marsRover.impl.missionImpl <em>mission</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.robotFinal.marsRover.impl.missionImpl
     * @see org.xtext.robotFinal.marsRover.impl.MarsRoverPackageImpl#getmission()
     * @generated
     */
    EClass MISSION = eINSTANCE.getmission();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MISSION__NAME = eINSTANCE.getmission_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference MISSION__TYPE = eINSTANCE.getmission_Type();

    /**
     * The meta object literal for the '{@link org.xtext.robotFinal.marsRover.impl.avoid_obstaclesImpl <em>avoid obstacles</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.robotFinal.marsRover.impl.avoid_obstaclesImpl
     * @see org.xtext.robotFinal.marsRover.impl.MarsRoverPackageImpl#getavoid_obstacles()
     * @generated
     */
    EClass AVOID_OBSTACLES = eINSTANCE.getavoid_obstacles();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AVOID_OBSTACLES__NAME = eINSTANCE.getavoid_obstacles_Name();

    /**
     * The meta object literal for the '<em><b>Sensors</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AVOID_OBSTACLES__SENSORS = eINSTANCE.getavoid_obstacles_Sensors();

    /**
     * The meta object literal for the '{@link org.xtext.robotFinal.marsRover.impl.ultraImpl <em>ultra</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.robotFinal.marsRover.impl.ultraImpl
     * @see org.xtext.robotFinal.marsRover.impl.MarsRoverPackageImpl#getultra()
     * @generated
     */
    EClass ULTRA = eINSTANCE.getultra();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ULTRA__NAME = eINSTANCE.getultra_Name();

    /**
     * The meta object literal for the '<em><b>Distance</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute ULTRA__DISTANCE = eINSTANCE.getultra_Distance();

    /**
     * The meta object literal for the '{@link org.xtext.robotFinal.marsRover.impl.bumpersImpl <em>bumpers</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.robotFinal.marsRover.impl.bumpersImpl
     * @see org.xtext.robotFinal.marsRover.impl.MarsRoverPackageImpl#getbumpers()
     * @generated
     */
    EClass BUMPERS = eINSTANCE.getbumpers();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute BUMPERS__NAME = eINSTANCE.getbumpers_Name();

    /**
     * The meta object literal for the '{@link org.xtext.robotFinal.marsRover.impl.detect_lakesImpl <em>detect lakes</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.robotFinal.marsRover.impl.detect_lakesImpl
     * @see org.xtext.robotFinal.marsRover.impl.MarsRoverPackageImpl#getdetect_lakes()
     * @generated
     */
    EClass DETECT_LAKES = eINSTANCE.getdetect_lakes();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DETECT_LAKES__NAME = eINSTANCE.getdetect_lakes_Name();

    /**
     * The meta object literal for the '<em><b>Number of lakes</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DETECT_LAKES__NUMBER_OF_LAKES = eINSTANCE.getdetect_lakes_Number_of_lakes();

    /**
     * The meta object literal for the '<em><b>Lakes colors</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DETECT_LAKES__LAKES_COLORS = eINSTANCE.getdetect_lakes_Lakes_colors();

    /**
     * The meta object literal for the '<em><b>After examinating</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DETECT_LAKES__AFTER_EXAMINATING = eINSTANCE.getdetect_lakes_After_examinating();

    /**
     * The meta object literal for the '{@link org.xtext.robotFinal.marsRover.impl.detect_rocksImpl <em>detect rocks</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.robotFinal.marsRover.impl.detect_rocksImpl
     * @see org.xtext.robotFinal.marsRover.impl.MarsRoverPackageImpl#getdetect_rocks()
     * @generated
     */
    EClass DETECT_ROCKS = eINSTANCE.getdetect_rocks();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DETECT_ROCKS__NAME = eINSTANCE.getdetect_rocks_Name();

    /**
     * The meta object literal for the '<em><b>Number of rocks</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute DETECT_ROCKS__NUMBER_OF_ROCKS = eINSTANCE.getdetect_rocks_Number_of_rocks();

    /**
     * The meta object literal for the '<em><b>After examinating</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference DETECT_ROCKS__AFTER_EXAMINATING = eINSTANCE.getdetect_rocks_After_examinating();

    /**
     * The meta object literal for the '{@link org.xtext.robotFinal.marsRover.impl.push_obstaclesImpl <em>push obstacles</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.robotFinal.marsRover.impl.push_obstaclesImpl
     * @see org.xtext.robotFinal.marsRover.impl.MarsRoverPackageImpl#getpush_obstacles()
     * @generated
     */
    EClass PUSH_OBSTACLES = eINSTANCE.getpush_obstacles();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PUSH_OBSTACLES__NAME = eINSTANCE.getpush_obstacles_Name();

    /**
     * The meta object literal for the '{@link org.xtext.robotFinal.marsRover.impl.after_actionImpl <em>after action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.robotFinal.marsRover.impl.after_actionImpl
     * @see org.xtext.robotFinal.marsRover.impl.MarsRoverPackageImpl#getafter_action()
     * @generated
     */
    EClass AFTER_ACTION = eINSTANCE.getafter_action();

    /**
     * The meta object literal for the '<em><b>Action</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AFTER_ACTION__ACTION = eINSTANCE.getafter_action_Action();

    /**
     * The meta object literal for the '<em><b>Indicate</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference AFTER_ACTION__INDICATE = eINSTANCE.getafter_action_Indicate();

    /**
     * The meta object literal for the '{@link org.xtext.robotFinal.marsRover.impl.indicationImpl <em>indication</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.robotFinal.marsRover.impl.indicationImpl
     * @see org.xtext.robotFinal.marsRover.impl.MarsRoverPackageImpl#getindication()
     * @generated
     */
    EClass INDICATION = eINSTANCE.getindication();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute INDICATION__NAME = eINSTANCE.getindication_Name();

    /**
     * The meta object literal for the '<em><b>Type</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference INDICATION__TYPE = eINSTANCE.getindication_Type();

    /**
     * The meta object literal for the '{@link org.xtext.robotFinal.marsRover.impl.soundImpl <em>sound</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.robotFinal.marsRover.impl.soundImpl
     * @see org.xtext.robotFinal.marsRover.impl.MarsRoverPackageImpl#getsound()
     * @generated
     */
    EClass SOUND = eINSTANCE.getsound();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SOUND__NAME = eINSTANCE.getsound_Name();

    /**
     * The meta object literal for the '<em><b>Duration</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SOUND__DURATION = eINSTANCE.getsound_Duration();

    /**
     * The meta object literal for the '<em><b>Frequency</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SOUND__FREQUENCY = eINSTANCE.getsound_Frequency();

    /**
     * The meta object literal for the '{@link org.xtext.robotFinal.marsRover.impl.messageImpl <em>message</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.robotFinal.marsRover.impl.messageImpl
     * @see org.xtext.robotFinal.marsRover.impl.MarsRoverPackageImpl#getmessage()
     * @generated
     */
    EClass MESSAGE = eINSTANCE.getmessage();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MESSAGE__NAME = eINSTANCE.getmessage_Name();

    /**
     * The meta object literal for the '<em><b>Msg</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute MESSAGE__MSG = eINSTANCE.getmessage_Msg();

    /**
     * The meta object literal for the '{@link org.xtext.robotFinal.marsRover.impl.color_indicationImpl <em>color indication</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.robotFinal.marsRover.impl.color_indicationImpl
     * @see org.xtext.robotFinal.marsRover.impl.MarsRoverPackageImpl#getcolor_indication()
     * @generated
     */
    EClass COLOR_INDICATION = eINSTANCE.getcolor_indication();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLOR_INDICATION__NAME = eINSTANCE.getcolor_indication_Name();

    /**
     * The meta object literal for the '<em><b>Color</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLOR_INDICATION__COLOR = eINSTANCE.getcolor_indication_Color();

    /**
     * The meta object literal for the '{@link org.xtext.robotFinal.marsRover.impl.parkImpl <em>park</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.robotFinal.marsRover.impl.parkImpl
     * @see org.xtext.robotFinal.marsRover.impl.MarsRoverPackageImpl#getpark()
     * @generated
     */
    EClass PARK = eINSTANCE.getpark();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute PARK__NAME = eINSTANCE.getpark_Name();

    /**
     * The meta object literal for the '{@link org.xtext.robotFinal.marsRover.impl.avoid_lakesImpl <em>avoid lakes</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.robotFinal.marsRover.impl.avoid_lakesImpl
     * @see org.xtext.robotFinal.marsRover.impl.MarsRoverPackageImpl#getavoid_lakes()
     * @generated
     */
    EClass AVOID_LAKES = eINSTANCE.getavoid_lakes();

    /**
     * The meta object literal for the '<em><b>Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute AVOID_LAKES__NAME = eINSTANCE.getavoid_lakes_Name();

    /**
     * The meta object literal for the '{@link org.xtext.robotFinal.marsRover.Color <em>Color</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.robotFinal.marsRover.Color
     * @see org.xtext.robotFinal.marsRover.impl.MarsRoverPackageImpl#getColor()
     * @generated
     */
    EEnum COLOR = eINSTANCE.getColor();

    /**
     * The meta object literal for the '{@link org.xtext.robotFinal.marsRover.LED_Color <em>LED Color</em>}' enum.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.xtext.robotFinal.marsRover.LED_Color
     * @see org.xtext.robotFinal.marsRover.impl.MarsRoverPackageImpl#getLED_Color()
     * @generated
     */
    EEnum LED_COLOR = eINSTANCE.getLED_Color();

  }

} //MarsRoverPackage
