/**
 * generated by Xtext 2.12.0
 */
package org.xtext.robotFinal.marsRover;

import org.eclipse.emf.ecore.EFactory;

/**
 * <!-- begin-user-doc -->
 * The <b>Factory</b> for the model.
 * It provides a create method for each non-abstract class of the model.
 * <!-- end-user-doc -->
 * @see org.xtext.robotFinal.marsRover.MarsRoverPackage
 * @generated
 */
public interface MarsRoverFactory extends EFactory
{
  /**
   * The singleton instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  MarsRoverFactory eINSTANCE = org.xtext.robotFinal.marsRover.impl.MarsRoverFactoryImpl.init();

  /**
   * Returns a new object of class '<em>Robot</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>Robot</em>'.
   * @generated
   */
  Robot createRobot();

  /**
   * Returns a new object of class '<em>mission</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>mission</em>'.
   * @generated
   */
  mission createmission();

  /**
   * Returns a new object of class '<em>avoid obstacles</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>avoid obstacles</em>'.
   * @generated
   */
  avoid_obstacles createavoid_obstacles();

  /**
   * Returns a new object of class '<em>ultra</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>ultra</em>'.
   * @generated
   */
  ultra createultra();

  /**
   * Returns a new object of class '<em>bumpers</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>bumpers</em>'.
   * @generated
   */
  bumpers createbumpers();

  /**
   * Returns a new object of class '<em>detect lakes</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>detect lakes</em>'.
   * @generated
   */
  detect_lakes createdetect_lakes();

  /**
   * Returns a new object of class '<em>detect rocks</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>detect rocks</em>'.
   * @generated
   */
  detect_rocks createdetect_rocks();

  /**
   * Returns a new object of class '<em>push obstacles</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>push obstacles</em>'.
   * @generated
   */
  push_obstacles createpush_obstacles();

  /**
   * Returns a new object of class '<em>after action</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>after action</em>'.
   * @generated
   */
  after_action createafter_action();

  /**
   * Returns a new object of class '<em>indication</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>indication</em>'.
   * @generated
   */
  indication createindication();

  /**
   * Returns a new object of class '<em>sound</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>sound</em>'.
   * @generated
   */
  sound createsound();

  /**
   * Returns a new object of class '<em>message</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>message</em>'.
   * @generated
   */
  message createmessage();

  /**
   * Returns a new object of class '<em>color indication</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>color indication</em>'.
   * @generated
   */
  color_indication createcolor_indication();

  /**
   * Returns a new object of class '<em>park</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>park</em>'.
   * @generated
   */
  park createpark();

  /**
   * Returns a new object of class '<em>avoid lakes</em>'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return a new object of class '<em>avoid lakes</em>'.
   * @generated
   */
  avoid_lakes createavoid_lakes();

  /**
   * Returns the package supported by this factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the package supported by this factory.
   * @generated
   */
  MarsRoverPackage getMarsRoverPackage();

} //MarsRoverFactory
