/**
 * generated by Xtext 2.12.0
 */
package org.xtext.robotFinal.marsRover;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Robot</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.xtext.robotFinal.marsRover.Robot#getName <em>Name</em>}</li>
 *   <li>{@link org.xtext.robotFinal.marsRover.Robot#getSlave_address <em>Slave address</em>}</li>
 *   <li>{@link org.xtext.robotFinal.marsRover.Robot#getDrive_speed <em>Drive speed</em>}</li>
 *   <li>{@link org.xtext.robotFinal.marsRover.Robot#getSpecial_speed <em>Special speed</em>}</li>
 *   <li>{@link org.xtext.robotFinal.marsRover.Robot#getMissions <em>Missions</em>}</li>
 * </ul>
 *
 * @see org.xtext.robotFinal.marsRover.MarsRoverPackage#getRobot()
 * @model
 * @generated
 */
public interface Robot extends EObject
{
  /**
   * Returns the value of the '<em><b>Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Name</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Name</em>' attribute.
   * @see #setName(String)
   * @see org.xtext.robotFinal.marsRover.MarsRoverPackage#getRobot_Name()
   * @model
   * @generated
   */
  String getName();

  /**
   * Sets the value of the '{@link org.xtext.robotFinal.marsRover.Robot#getName <em>Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Name</em>' attribute.
   * @see #getName()
   * @generated
   */
  void setName(String value);

  /**
   * Returns the value of the '<em><b>Slave address</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Slave address</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Slave address</em>' attribute.
   * @see #setSlave_address(String)
   * @see org.xtext.robotFinal.marsRover.MarsRoverPackage#getRobot_Slave_address()
   * @model
   * @generated
   */
  String getSlave_address();

  /**
   * Sets the value of the '{@link org.xtext.robotFinal.marsRover.Robot#getSlave_address <em>Slave address</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Slave address</em>' attribute.
   * @see #getSlave_address()
   * @generated
   */
  void setSlave_address(String value);

  /**
   * Returns the value of the '<em><b>Drive speed</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Drive speed</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Drive speed</em>' attribute.
   * @see #setDrive_speed(int)
   * @see org.xtext.robotFinal.marsRover.MarsRoverPackage#getRobot_Drive_speed()
   * @model
   * @generated
   */
  int getDrive_speed();

  /**
   * Sets the value of the '{@link org.xtext.robotFinal.marsRover.Robot#getDrive_speed <em>Drive speed</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Drive speed</em>' attribute.
   * @see #getDrive_speed()
   * @generated
   */
  void setDrive_speed(int value);

  /**
   * Returns the value of the '<em><b>Special speed</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Special speed</em>' attribute isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Special speed</em>' attribute.
   * @see #setSpecial_speed(int)
   * @see org.xtext.robotFinal.marsRover.MarsRoverPackage#getRobot_Special_speed()
   * @model
   * @generated
   */
  int getSpecial_speed();

  /**
   * Sets the value of the '{@link org.xtext.robotFinal.marsRover.Robot#getSpecial_speed <em>Special speed</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Special speed</em>' attribute.
   * @see #getSpecial_speed()
   * @generated
   */
  void setSpecial_speed(int value);

  /**
   * Returns the value of the '<em><b>Missions</b></em>' containment reference list.
   * The list contents are of type {@link org.xtext.robotFinal.marsRover.mission}.
   * <!-- begin-user-doc -->
   * <p>
   * If the meaning of the '<em>Missions</em>' containment reference list isn't clear,
   * there really should be more of a description here...
   * </p>
   * <!-- end-user-doc -->
   * @return the value of the '<em>Missions</em>' containment reference list.
   * @see org.xtext.robotFinal.marsRover.MarsRoverPackage#getRobot_Missions()
   * @model containment="true"
   * @generated
   */
  EList<mission> getMissions();

} // Robot
