/**
 * generated by Xtext 2.12.0
 */
package org.xtext.robotFinal.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;
import org.xtext.robotFinal.ui.AbstractMarsRoverUiModule;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class MarsRoverUiModule extends AbstractMarsRoverUiModule {
  public MarsRoverUiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
