/**
 * generated by Xtext 2.12.0
 */
package org.xtext.robotFinal.scoping;

import org.xtext.robotFinal.scoping.AbstractMarsRoverScopeProvider;

/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
@SuppressWarnings("all")
public class MarsRoverScopeProvider extends AbstractMarsRoverScopeProvider {
}
