/**
 * generated by Xtext 2.12.0
 */
package org.xtext.robotFinal;

import org.xtext.robotFinal.AbstractMarsRoverRuntimeModule;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class MarsRoverRuntimeModule extends AbstractMarsRoverRuntimeModule {
}
