/**
 * generated by Xtext 2.12.0
 */
package org.xtext.robotFinal.ide;

import org.xtext.robotFinal.ide.AbstractMarsRoverIdeModule;

/**
 * Use this class to register ide components.
 */
@SuppressWarnings("all")
public class MarsRoverIdeModule extends AbstractMarsRoverIdeModule {
}
