/**
 * generated by Xtext 2.12.0
 */
package org.xtext.robotFinal.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.robotFinal.MarsRoverRuntimeModule;
import org.xtext.robotFinal.MarsRoverStandaloneSetup;
import org.xtext.robotFinal.ide.MarsRoverIdeModule;

/**
 * Initialization support for running Xtext languages as language servers.
 */
@SuppressWarnings("all")
public class MarsRoverIdeSetup extends MarsRoverStandaloneSetup {
  @Override
  public Injector createInjector() {
    MarsRoverRuntimeModule _marsRoverRuntimeModule = new MarsRoverRuntimeModule();
    MarsRoverIdeModule _marsRoverIdeModule = new MarsRoverIdeModule();
    return Guice.createInjector(Modules2.mixin(_marsRoverRuntimeModule, _marsRoverIdeModule));
  }
}
